---
# ==============================================================================
# Task file: kubeconfig.yml
#
# Purpose
# -------
# Copy the Kubernetes client configuration from the K3s server to the local
# management workstation.
#
# kubectl uses this file to talk to the Kubernetes API server.
# ==============================================================================

- name: Read the server administrator kubeconfig
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_server_kubeconfig
  no_log: true

- name: Manage the local administrator kubeconfig
  ansible.builtin.copy:
    content: >-
      {{ k3s_server_kubeconfig.content | b64decode |
         replace('127.0.0.1', ansible_host) }}
    dest: "{{ playbook_dir }}/../kubeconfig"
    mode: "0600"
  delegate_to: localhost
  become: false
  no_log: true

- name: Restrict local administrator kubeconfig permissions
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../kubeconfig"
    mode: "0600"
  delegate_to: localhost
  become: false
