---
# ==============================================================================
# Task file: kubeconfig.yml
#
# Purpose
# -------
# Copy the Kubernetes client configuration from the K3s server to the local
# management workstation.
#
# kubectl uses this file to talk to the Kubernetes API server.
# ==============================================================================

- name: Fetch kubeconfig from K3s server
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ playbook_dir }}/../kubeconfig"
    flat: true

- name: Replace localhost with server IP in kubeconfig
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/../kubeconfig"
    regexp: '127.0.0.1'
    replace: "{{ ansible_host }}"
  delegate_to: localhost
  become: false