---
# ==============================================================================
# Home lab inventory
#
# Purpose
# -------
# This file defines which machines exist in the environment.
#
# Important principle:
#
#   Inventory describes WHERE automation runs.
#   Playbooks describe WHAT automation does.
#
# Here, "pis" is a group name. It is not a hostname.
# ==============================================================================

all:
  children:

    # Raspberry Pi 4 Model B nodes.
    #
    # These are the first four physical machines in the home lab.
    # Later we can add more groups, for example:
    #
    #   cm4:
    #   rk1:
    #   storage:
    #   ai:
    #
    pis:
      hosts:
        pi4mB01:
        pi4mB02:
        pi4mB03:
        pi4mB04:

    # The K3s server/control-plane
    #
    k3s_server:
      hosts:
        pi4mB01:
    
    # The K3 workers
    #
    k3s_agents:
      hosts:
        pi4mB02:
        pi4mB03:
        pi4mB04:
