apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: networking
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: homelab-networking
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pihole
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
